- hosts: tomcat
  become: true
  vars:
    tomcat_version: 9.0.40

    tomcat_permissions_production: True

    tomcat_users:
      - username: "tomcat"
        password: "tomcat"
        roles: "tomcat,admin,manager,manager-gui"
      - username: "tomcat2"
        password: "tomcat2"
        roles: "tomcat"
  roles:
    - role: zaxos.tomcat-ansible-role
